server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application.name: statistic-service
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
hosts:
  account-service: http://localhost
  account-service-port: 8080
  account-service-prefix: api
