server:
  port: 8081
  servlet:
    context-path: /stat

spring:
  application.name: statistic-service

hosts:
  account-service: http://localhost
  account-service-port: 8080
  account-service-prefix: api