server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application.name: notification-service
  mail:
    host: test
    port: 1
    username: test
    password: test

hosts:
  account-service: http://localhost
  account-service-port: 8080
  account-service-prefix: api
